name: Stevie Zollo
description: "Stevie Zollo's Blog - posts about my work in IT. Virtualization, Infrastructure, Cloud, DevOps and Bitcoin"

url: http://steviezollo.it
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
pygments: true
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html